### ISSUE TITLE
bug: Translation problems on `Uydu` layer.

### ISSUE THREAD

**Issue by sercanerhan** [acikkaynak/deprem-yardim-frontend#1019]
## Bug Definition
There are two problem with the translation on the `Uydu` Layer:

1. Layer Name: Should be `Satellite` instead of Uydu in **EN** version.
2. There is a classification type named `Destroyed`  which should be renamed as `collapsed`.

There should be a better translation for the 1st item since we do not provide the Satellite imagery. Later on we need to find a better naming to tell the user, this is a result/prediction of the status of the selected building based on Satellite imagery. 

![image](https://user-images.githubusercontent.com/3420568/219055525-761a33c9-4147-4c7f-a68b-c7b430c25280.png)

** discord username: @sercanerhan#0543 **

## Bug environment
> Describe the environment produces the bug.
afetharita.com
## Describe how you are producing the bug step by step

3. Click '....' 
4. Scroll to '....' 
5. Bug appears

## Expected Behaviour
A clear and short text to decribe the expected behaviour.

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: [for example iOS]
- Browser [for example, safari]
- Version [for example 22]

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

## Additional Context
Add any other context about the bug here

**Comment by absolutezero13** [comment]
@sercanerhan Both classification type and layer name coming from backend. The same thing happening on hot meal, pharmacy etc. Their layers are also Turkish. We can translate if we learn all possible values that might come from backend.

**Comment by sercanerhan** [comment]
@absolutezero13 could you please share the list of values (with their types if needed such as `layerName`) that needs to be translated here? I'd be happy to translate them.

**Comment by absolutezero13** [comment]
@sercanerhan Well we don't know, or at least I don't, for example for hot meal there is "Onaylanmadı" value for layer. We don't know about other possible values, maybe we can ask backend devs.

**Comment by sercanerhan** [comment]
Can we continue to fix the `Destroyed` within the scope of this issue? I'll try to learn the other values as you suggested 👍

**Comment by absolutezero13** [comment]
@sercanerhan is there some spesific issue with the `Destroyed` word ? If so, I can create a pull request but otherwise PR might not be approved since it's not ideal solution.

**Comment by sercanerhan** [comment]
Yes definitely.  It's so rude, to mention a building that people died under it as destroyed. It's not a mission to be completed. Correct English would be `Collapsed`. @absolutezero13

**Comment by absolutezero13** [comment]
@sercanerhan I created a PR, can you check #1023

**Comment by sercanerhan** [comment]
verified & approved. thank you @absolutezero13 :+1:

**Comment by yavuzKomecoglu** [comment]
Hi,
1- The "satellite" icon on the map gives a "receiver" image. Instead, an icon representing the wrecked buildings can be used, similar to the one in the appendix.
Recommended icon: http://yavuzkomecoglu.com/afetharita/icon_earthquake_building.png

2- In the same way, it can be replaced with an image with a wrecked building icon instead of a satellite image in the layer menu.

3- The word "wrecked buildings" can be used instead of the word "satellite" in the layer menu

4- When the pin location is clicked, it can be changed as follows in the status section of the detail popup. Except for the following two cases, if different values are coming from the backend API, the corresponding ones can be updated.

- API damage values;
  - 1- API value: "Damaged" - TR: "yıkılmış", ENG: "wrecked"
  - 2- API value: "Possibly damaged" - TR: "muhtemelen hasarlı/yıkılmış", ENG: "probably Collapsed"

**Comment by sercanerhan** [comment]
It would be better to use different icon types depending on the `Damaged`, `Possible Damaged`, `Probably Collapsed`. I'll share this with the UX team. thank you @yavuzKomecoglu

**Comment by sercanerhan** [comment]
It would be better to use different icon types depending on the `Damaged`, `Possible Damaged`, `Probably Collapsed`. I'll share this with the UX team. thank you @yavuzKomecoglu
